### ISSUE TITLE
No CORS support

### ISSUE THREAD

**Issue by michelemottini** [department-of-veterans-affairs/lighthouse#8]
The sandbox FHIR end point https://fhir.healow.com/FHIRServer/fhir/BJFCBD does not support CORS, so it cannot be used by HTML+JavaScript apps

( Is this the right place where to file issues / questions ? )

**Comment by JohnMoehrke** [comment]
It is common for FHIR sandboxes to enable CORS for this piloting purpose. This is the recommendation from Argonaut and their SMART-on-FHIR.  However in the long term, a security assessment should determine production need or CORS. That would be based on expected use-cases that CORS enables, vs the risks that CORS also enables.

**Comment by michelemottini** [comment]
...our apps cannot  works without CORS, so without that we cannot test the end point (nor use it in production in the future)...

**Comment by myklegard** [comment]
Hey @michelemottini @JohnMoehrke that isn't our end point. Not sure who owns it, but maybe try the team that owns the domain.

**Comment by michelemottini** [comment]
What is you end point?
